import type {PreviewSnapshot} from './index.ts';
import {previewClient} from './client.ts';

const css = `
:root{--ink:#1a3546;--muted:#5d7280;--paper:#f9fbfd;--line:#cfdae2;--teal:#167668;--copper:#bd6a27;font:14px/1.5 "Segoe UI",Arial,sans-serif;color:var(--ink);background:#e7edf2;color-scheme:light}
*{box-sizing:border-box}body{margin:0}button,select{font:inherit;color:inherit}button{cursor:pointer;background:var(--paper);border:1px solid var(--line);border-radius:5px;padding:7px 12px}button:hover{border-color:var(--teal)}button:disabled{opacity:.5;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid var(--teal);outline-offset:3px}
header{display:flex;align-items:center;gap:24px;padding:18px 28px;border-bottom:1px solid var(--line);background:var(--paper)}.brand{font:600 20px/1 ui-monospace,monospace;letter-spacing:-1px}.brand span{color:var(--teal)}h1{font-size:20px;line-height:1.3;margin:0;font-weight:600;overflow-wrap:anywhere}h2{font-size:12px;text-transform:uppercase;letter-spacing:1.2px;margin:0 0 14px;color:var(--muted)}h3{margin:0;font-size:20px}h4{font-size:12px;margin:20px 0 8px;text-transform:uppercase;letter-spacing:.6px}.muted{color:var(--muted)}.source{font:12px/1.5 ui-monospace,monospace;overflow-wrap:anywhere}.header-title{flex:1;min-width:0}.status{display:flex;align-items:center;gap:8px;font-size:12px}.status:before{content:"";width:8px;height:8px;background:var(--teal);border-radius:50%}.status[data-state=error]:before{background:#9c432a}.status[data-state=building]:before{background:var(--copper)}.mode{font-size:11px;text-transform:uppercase;letter-spacing:.8px;color:var(--muted)}
.workbench{display:grid;grid-template-columns:220px minmax(0,1fr) 280px;min-height:calc(100vh - 82px)}aside{background:var(--paper);padding:22px 18px;border-right:1px solid var(--line)}aside.right{border-left:1px solid var(--line);border-right:0;overflow-wrap:anywhere}.layer{display:flex;align-items:center;gap:8px;cursor:pointer;margin:10px 0;font:12px/1.5 ui-monospace,monospace;overflow-wrap:anywhere}.layer input{accent-color:var(--teal);margin:0}.swatch{width:9px;height:9px;border-radius:2px;flex-shrink:0}.sidebar-note{font-size:12px;border-top:1px solid var(--line);padding-top:16px;margin-top:22px}.parts-title{margin-top:30px}.part{width:100%;display:grid;grid-template-columns:38px 1fr;text-align:left;gap:1px 6px;border-color:transparent;background:transparent;padding:10px 8px;margin:3px 0}.part strong{grid-row:span 2;align-self:center;font-family:ui-monospace,monospace}.part span{font-size:12px;overflow-wrap:anywhere}.part small{font-size:11px}.part[aria-pressed=true]{background:#e3f0ea;border-color:#a9cec0}
main{min-width:0;padding:20px 22px}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.toolbar select{max-width:180px;border:1px solid var(--line);border-radius:5px;background:var(--paper);padding:7px}.controls{display:flex;align-items:center;gap:6px}.zoom-level{min-width:44px;text-align:center;font:12px ui-monospace,monospace}.scene-wrap{position:relative;border:1px solid #c0d0d9;border-radius:8px;background-color:#f0f5f7;background-image:radial-gradient(#b8cbd4 .8px,transparent .8px);background-size:20px 20px;overflow:hidden}.scene{height:clamp(400px,64vh,850px);min-height:400px}.scene svg{width:100%;height:100%;display:block;touch-action:none;cursor:grab}.scene svg:active{cursor:grabbing}.scene svg .selected{filter:drop-shadow(0 0 .15px #167668)}.scene svg .net-match{fill:#d34771;opacity:1}.scene svg .dimmed{opacity:.18}.scene-caption{position:absolute;bottom:10px;left:14px;font:11px ui-monospace,monospace;color:var(--muted);pointer-events:none;background:#f0f5f7e8;padding:3px 7px;border-radius:3px}.scene svg text{user-select:none}.summary{font:12px ui-monospace,monospace;margin-top:12px}.exports{display:flex;gap:8px}.detail-row{display:flex;align-items:baseline;justify-content:space-between;gap:14px;margin:7px 0;font-size:12px}.detail-row span:last-child{text-align:right;overflow-wrap:anywhere}.part-name{font:12px ui-monospace,monospace}.connection{display:block;width:100%;text-align:left;margin:5px 0;font:12px ui-monospace,monospace}.check-status{font-size:11px;color:var(--muted)}
.error{background:#fff1eb;border:1px solid #e8b7a2;border-radius:6px;padding:14px 18px;margin-bottom:16px}.error strong{color:#9c432a}.error pre{white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.6 ui-monospace,monospace;max-height:260px;overflow:auto}.stale{color:#9c432a;font-size:12px;margin:8px 0}.diagnostics{margin-top:22px;border-top:1px solid var(--line);padding-top:14px}.diagnostics summary{cursor:pointer;font-size:13px;font-weight:600}.diagnostic{padding:12px 0;border-bottom:1px solid var(--line);overflow-wrap:anywhere}.diagnostic strong{font:11px ui-monospace,monospace;color:var(--muted)}.diagnostic p{margin:5px 0;font-size:12px}[hidden]{display:none!important}
@media(max-width:1100px){.workbench{grid-template-columns:200px minmax(0,1fr)}aside.right{grid-column:1/-1;border-left:0;border-top:1px solid var(--line)}.right #part-details{max-width:720px}.detail-row{justify-content:flex-start}.detail-row span:first-child{min-width:160px}.toolbar{flex-wrap:wrap}}
@media(max-width:650px){header{padding:14px 16px;gap:12px;flex-wrap:wrap}.brand{font-size:17px}.header-title{min-width:160px}.workbench{display:flex;flex-direction:column}aside{border-right:0;border-bottom:1px solid var(--line)}aside.left{order:2}aside.right{order:3}main{order:1;padding:14px}.scene{height:400px}.toolbar{gap:8px}.parts-title{margin-top:20px}.status{font-size:11px}.exports button{font-size:12px}h1{font-size:17px}}
`;

export function previewHtml(snapshot: PreviewSnapshot): string {
  // '<' escaping protects the embedded JSON even when labels contain </script>.
  const payload = JSON.stringify(snapshot).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Board preview · react-pcb</title><style>${css}</style></head>
<body><header><div class="brand">react<span>pcb</span></div><div class="header-title"><h1 id="board-title">Board preview</h1><div id="source" class="source muted"></div></div><span id="mode" class="mode"></span><span id="status" class="status" role="status">Compiling…</span></header>
<div class="workbench"><aside class="left"><h2>Board layers</h2><div id="layers"></div><p class="sidebar-note muted">Front view. Back-side parts use their resolved placement and layers.</p><h2 class="parts-title">Parts</h2><div id="parts"></div></aside>
<main><div id="build-error" class="error" role="alert" hidden><strong>Board compilation failed</strong><pre id="error-message"></pre></div><p id="stale-label" class="stale"></p>
<div class="toolbar"><div class="controls"><button id="zoom-out" aria-label="Zoom out">−</button><span id="zoom-level" class="zoom-level">100%</span><button id="zoom-in" aria-label="Zoom in">+</button><button id="fit">Fit board</button></div><label class="muted">Highlight <select id="net" aria-label="Highlight net"><option>All nets</option></select></label></div>
<div class="scene-wrap"><div id="scene" class="scene"></div><span class="scene-caption">Placement preview · routing unresolved</span></div>
<div class="toolbar" style="margin-top:14px"><div id="summary" class="summary"></div><div class="exports"><button id="download-svg">Save SVG</button><button id="download-ir">Save IR</button></div></div>
<details class="diagnostics"><summary>Diagnostics <span id="diagnostic-count">0</span></summary><div id="diagnostic-list"></div></details></main>
<aside class="right"><h2>Part inspection</h2><div id="part-details"></div></aside></div>
<script type="application/json" id="preview-data">${payload}</script><script>(${previewClient.toString()})();</script></body></html>\n`;
}
